first commit
AngelinaMelek/Mastery pull request #3
Opened 2022-04-27 18:39 UTC by AngelinaMelek

2022-04-28 13:34 UTC, aabrazouski requested changes

2022-04-28 13:34 UTC, aabrazouski commented on HTML/Task2/index.html
> +        <tfoot>
Внутри `tfoot` так же должен быть `tr` с `td`  внутри

2022-04-28 13:34 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <table id="table2">
Сразу внутри `table` не может лежать `td`.
Структура всегда одинакова:
`table` -> `thead | tbody | tfoot` -> `tr` -> `td | th`

2022-04-28 13:34 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td id="nested1">
1. Лучше сделать это без дополнительной таблицы, а двумя `td`, при этом `th` для этой колонки объединить используя атрибут `colspan`.
2. Индентификаторы стоит задавать более осмысленные, но в случае с `td` он неуместен, т.к. таких ячеек будет много (по количеству ячеек), соотвственно айдишники будут повторяться, а определенный айди должен быть **только один** на всей странице

2022-04-28 13:34 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <li><a href="#">&gt</a></li>
`&gt;` `&lt;`

2022-04-29 14:36 UTC, aabrazouski requested changes

2022-04-29 14:36 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td><span>.</span><span>.</span><span>.</span></td>
Это должно быть обернуто в кнопку

2022-04-29 14:36 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td colspan="9"></td>
Тут должна быть одна `td` `colspan="10"`

2022-04-29 14:36 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td>&nbsp;</td>
Эту пустые ячейки не нужны, скрин ридер будет просто тратить время на его прочтение, не давая никакой информации. 
В первую строку всей записи нужно переместить ячейки от Status до последней ячеки и задать атрибут `rowspan="2"`

2022-05-01 06:09 UTC, AngelinaMelek commented on HTML/Task2/index.html
> +                <td colspan="9"></td>
При `colspan='10'` кнопки переносит в 11ю колонку

2022-05-04 15:55 UTC, aabrazouski requested changes

2022-05-04 15:55 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td colspan="10"></td>
colspan=10 + ещё одна td получается 11 ячеек.
Да и эта пустая ячейка не нужна. Не важно что список оказывается слева, в будущем можно стилизовать

2022-05-04 15:55 UTC, aabrazouski commented on HTML/Task2/index.html
> +              <th rowspan="4">Status</th>
А для чего здесь эти случайные числа в атрибуте rowspan?)
Они не нужны

2022-05-04 15:55 UTC, aabrazouski commented on HTML/Task2/index.html
> +                <td>Done</td>
Эти 4 ячейки нужно поместить в первую строку и добавить rowspan=2. Так текст тоже отцентрируется

2022-05-09 06:04 UTC, merged